apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nobby-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - nobby-a4aedadfe4.northeurope.cloudapp.azure.com
    secretName: tls-secret-prod
  rules:
  - host: nobby-a4aedadfe4.northeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nobby-service
          servicePort: 3000
      - path: /solr
        backend:
          serviceName: solr-service
          servicePort: 8983
